### PR TITLE
Dutch Translation by @SmidtDeveloping

### PR DESCRIPTION
**Pull request by SmidtDeveloping**

### CODE REVIEW

**Comment by maximmax42** [comment]
Commenting so you know I've seen the PR. I will work on it tomorrow.

**Comment by maximmax42** [comment]
In the meantime, if you want to be credited with a link, please post it here.

**Comment by SmidtDeveloping** [comment]
> In the meantime, if you want to be credited with a link, please post it here.

You mean my website? For credits? its https://developingbyjulian.nl

**Comment by maximmax42** [comment]
Live at https://docs.customrp.xyz/v/nl.

**Pull request merged**
